# Generated by Django 4.0.6 on 2022-07-27 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
                ('tags', models.CharField(choices=[('Urgente', 'Urgente'), ('Saúde', 'Saúde'), ('Politica', 'Politica')], max_length=20, verbose_name='Tags')),
                ('data_pub', models.DateTimeField(verbose_name='Data de publicação')),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.autor')),
            ],
        ),
    ]
